# Setup
title:               mino
subtitle:            sai
tagline:             'sai mino choilog'
description:         '낭비한 시간에 대한 후회는 더 큰 시간 낭비이다. \n 우리 인생은 우리가 노력한 만큼 가치가 있다.'
url:                 https://saimino.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Choi Minho
  url:               
  email:             chlalsgh789@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
